
const data=await fetch('./data.json').then(r=>r.json());
const app=document.querySelector('#app'), nav=[...document.querySelectorAll('.bottom button')];
const drawer=document.querySelector('#drawer'),shade=document.querySelector('#shade');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setActive(v){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function close(){drawer.classList.remove('open');shade.classList.remove('open')}
function links(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go))}
function home(){
setActive('home');app.innerHTML=`<section class="cover"><div class="coverCopy"><div class="kicker">20. 7. – 5. 8. 2026</div><h1>Mise tří dobrodruhů</h1><p>Tokio, hora Fuji, čajový obřad, samurajové, jeleni, ostrovy, moře a sushi připravované přímo před námi. Sedmnáct dní, během kterých se Japonsko několikrát úplně promění.</p><div class="stats"><div class="stat"><b>17</b><small>dní</small></div><div class="stat"><b>7</b><small>kapitol</small></div><div class="stat"><b>4</b><small>Nozomi</small></div><div class="stat"><b>2</b><small>ostrovy</small></div></div><p style="margin-top:22px"><button class="btn" data-go="chapters">Otevřít dobrodružství</button></p></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">NAŠE CESTA</div><h2>Od neonu k moři a zpět</h2><div class="sub">Každá část cesty má úplně jinou náladu.</div></div></div><img class="routeImg" src="./assets/route.svg" alt="Mapa trasy"></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">CO ZAŽIJEME</div><h2>Tohle nebude obyčejná dovolená</h2></div></div><div class="grid">
<article class="card"><h3>Velkoměsto</h3><p>Shibuya, digitální teamLab a Akihabara, která vypadá jako kulisa z budoucnosti.</p></article>
<article class="card"><h3>Tradiční Japonsko</h3><p>Čajový obřad, samurajský workshop, chrámy a tisíce torii.</p></article>
<article class="card"><h3>Moře a ostrovy</h3><p>Mijadžima při západu slunce a dva pomalé dny na kolech a pláži Naošimy.</p></article>
</div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">KAPITOLY</div><h2>Sedm různých světů</h2></div></div><div class="grid">${data.cities.map(c=>chapterCard(c)).join('')}</div></section>`;links()}
function chapterCard(c){return `<article class="card chapterCard"><img src="./assets/chapter-${c.id}.svg" alt=""><div class="chapterText"><small>${esc(c.jp)}</small><h3>${esc(c.name)}</h3><p>${esc(c.tag)}</p><button class="btn" data-go="chapter-${c.id}">Otevřít</button></div></article>`}
function chapters(){setActive('chapters');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">PŘÍBĚH CESTY</div><h2>Kapitoly</h2><div class="sub">Krátké čtení pro Filipa, Nelu i tátu.</div></div></div><div class="grid">${data.cities.map(c=>chapterCard(c)).join('')}</div></section>`;links()}
function chapter(id){
setActive('chapters');const c=data.cities.find(x=>x.id===id);const ds=data.days.filter(d=>d.chapter===id || (id==='tokyo2'&&d.chapter==='tokyo2'));
app.innerHTML=`<section class="chapterHero"><img src="./assets/chapter-${c.id}.svg"><div><div class="kicker">${esc(c.jp)}</div><h1>${esc(c.name)}</h1><p>${esc(c.intro)}</p></div></section>
<section class="section"><div class="grid"><article class="card wide"><h2>Co nás čeká</h2><div class="tags">${c.highlights.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><p style="margin-top:18px">${esc(c.kids)}</p></article><article class="card"><h3>Ochutnáme</h3><div class="tags">${c.food.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">DNY V TÉTO KAPITOLE</div><h2>Konkrétní plán</h2></div></div><article class="card full">${ds.map(d=>`<div class="dayCard"><div class="date">${d.date}</div><div><b>${esc(d.title)}</b><p>${esc(d.story)}</p><button class="btn outline" data-go="day-${data.days.indexOf(d)}">Detail dne</button></div></div>`).join('')}</article></section>`;links()}
function days(){setActive('days');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">DEN PO DNI</div><h2>Praktický itinerář</h2><div class="sub">Příběh je nahoře, logistika zůstává vždy po ruce.</div></div></div><article class="card full">${data.days.map((d,i)=>`<div class="dayCard"><div class="date">${d.date}</div><div><b>${esc(d.title)}</b><p>${esc(d.city)} · ${esc(d.story)}</p><button class="btn outline" data-go="day-${i}">Otevřít</button></div></div>`).join('')}</article></section>`;links()}
function day(i){
setActive('days');const d=data.days[i];app.innerHTML=`<section class="chapterHero" style="height:430px"><img src="./assets/chapter-${d.chapter}.svg"><div><div class="kicker">${d.date} · ${esc(d.city)}</div><h1 style="font-size:clamp(42px,7vw,72px)">${esc(d.title)}</h1><p>${esc(d.story)}</p></div></section>
<section class="section"><div class="grid"><article class="card wide"><div class="timeline">${d.schedule.map(x=>`<div class="event"><div class="time">${esc(x[0])}</div><b>${esc(x[1])}</b><span>${esc(x[2])}</span></div>`).join('')}</div></article><article class="card"><h3>Mise dne</h3>${d.missions.map(x=>`<p>${esc(x)}</p>`).join('')}<h3>Ochutnat</h3><div class="tags">${d.food.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>${d.map?`<p><a class="btn" href="https://maps.apple.com/?q=${encodeURIComponent(d.map)}" target="_blank">Otevřít mapu</a></p>`:''}</article></div></section>
<section class="section"><div class="grid"><article class="card"><h3>Stav dne</h3><label class="check"><input type="checkbox" data-check="d${i}a"> Připraveno</label><label class="check"><input type="checkbox" data-check="d${i}b"> Splněno</label><label class="check"><input type="checkbox" data-check="d${i}c"> Máme fotku dne</label></article><article class="card wide"><h3>Naše poznámka</h3><textarea data-note="d${i}" placeholder="Nejlepší moment, překvapení, změna plánu…"></textarea></article></div></section>`;restore()}
function food(){setActive('food');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">JÍDLO</div><h2>Místa, která zapadají do naší trasy</h2><div class="sub">Ne žebříček nejdražších restaurací, ale konkrétní a dosažitelné zážitky.</div></div></div><div class="grid">${data.restaurants.map(r=>`<article class="card foodCard"><div class="city">${esc(r.city)}</div><h3>${esc(r.name)}</h3><p>${esc(r.why)}</p><div class="tags"><span class="tag">${esc(r.order)}</span></div><div class="when">${esc(r.when)}</div><p><a class="btn outline" href="https://maps.apple.com/?q=${encodeURIComponent(r.map)}" target="_blank">Mapa</a></p></article>`).join('')}</div></section>`}
function practical(){setActive('practical');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">PRAKTICKY</div><h2>Rezervace a poslední kontrola</h2></div></div><div class="grid"><article class="card wide"><h3>Pevné časy</h3>${data.reservations.map(r=>`<div class="res"><b>${r[0]}</b><span>${r[1]}</span><span>${esc(r[2])}</span></div>`).join('')}</article><article class="card"><h3>Před odletem</h3>${["Pasy a pojištění","eSIM","Suica","Adaptéry","Powerbanky","Pláštěnky a malé deštníky","SPF 50 a kšiltovky","Rezervace uložené offline"].map((x,i)=>`<label class="check"><input type="checkbox" data-check="p${i}"> ${x}</label>`).join('')}</article><article class="card full callout"><h3>Pravidlo tří</h3><p>Při každém přesunu: <b>mobil · peněženka/pas · batoh</b>. Nic dalšího není důležitější.</p></article></div></section>`;restore()}
function restore(){document.querySelectorAll('[data-check]').forEach(x=>{x.checked=localStorage.getItem('c'+x.dataset.check)==='1';x.onchange=()=>localStorage.setItem('c'+x.dataset.check,x.checked?'1':'0')});document.querySelectorAll('[data-note]').forEach(x=>{x.value=localStorage.getItem('n'+x.dataset.note)||'';x.oninput=()=>localStorage.setItem('n'+x.dataset.note,x.value)})}
function go(v){close();window.scrollTo(0,0);location.hash=v;if(v==='home')home();else if(v==='chapters')chapters();else if(v==='days')days();else if(v==='food')food();else if(v==='practical')practical();else if(v.startsWith('chapter-'))chapter(v.slice(8));else if(v.startsWith('day-'))day(Number(v.slice(4)));else home()}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector('#menu').onclick=()=>{drawer.classList.add('open');shade.classList.add('open')};document.querySelector('#close').onclick=close;shade.onclick=close;
document.querySelector('#drawerNav').innerHTML=[['home','Úvod'],['chapters','Kapitoly'],['days','Den po dni'],['food','Jídlo'],['practical','Prakticky'],...data.cities.map(c=>['chapter-'+c.id,c.name])].map(x=>`<button data-drawer="${x[0]}">${esc(x[1])}</button>`).join('');document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>go(b.dataset.drawer));
document.querySelector('#mode').onclick=()=>{const d=document.documentElement.dataset.dark==='1'?'0':'1';document.documentElement.dataset.dark=d;localStorage.setItem('dark',d)};document.documentElement.dataset.dark=localStorage.getItem('dark')||'0';
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');go(location.hash.slice(1)||'home');
