
const data=await fetch('./data.json').then(r=>r.json());
const app=document.querySelector('#app'), nav=[...document.querySelectorAll('.bottom button')];
const drawer=document.querySelector('#drawer'),shade=document.querySelector('#shade');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setActive(v){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function close(){drawer.classList.remove('open');shade.classList.remove('open')}
function links(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));document.querySelectorAll('[data-term]').forEach(x=>x.onclick=()=>showTerm(x.dataset.term))}
function chips(items){return `<div class="chips">${items.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`}
function glossaryReplace(text){
  let out=esc(text);
  for(const g of data.glossary){
    const re=new RegExp(`\\b${g.term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi');
    out=out.replace(re,m=>`<span class="term" data-term="${esc(g.term)}">${m}</span>`);
  }
  return out;
}
function chapterCard(c){return `<article class="card chapterCard click-card" tabindex="0" role="button" data-go="chapter-${c.id}"><img src="./assets/chapter-${c.id}.svg" alt=""><div class="chapterText"><small>${esc(c.jp)}</small><h3>${esc(c.name)}</h3><p>${esc(c.tag)}</p><span class="open-cue">Otevřít kapitolu →</span></div></article>`}
function home(){
setActive('home');app.innerHTML=`<section class="cover"><div class="coverCopy"><div class="kicker">20. 7. – 5. 8. 2026</div><h1>Mise tří dobrodruhů</h1><p>Tokio, hora Fuji, čajový obřad, samurajové, jeleni, ostrovy, moře a sushi připravované přímo před námi. Sedmnáct dní, během kterých se Japonsko několikrát úplně promění.</p><div class="stats"><div class="stat"><b>17</b><small>dní</small></div><div class="stat"><b>8</b><small>kapitol</small></div><div class="stat"><b>4</b><small>Nozomi</small></div><div class="stat"><b>2</b><small>ostrovy</small></div></div><p style="margin-top:22px"><button class="btn" data-go="chapters">Začít cestu →</button></p></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">NAŠE CESTA</div><h2>Od neonu k moři a zpět</h2><div class="sub">Na mobilu můžeš mapku posouvat prstem.</div></div></div><div class="routeWrap"><div class="routeScroll"><img class="routeImg" src="./assets/route.svg" alt="Mapa trasy"></div><div class="routeHint">← posuň mapu do stran →</div></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">CO ZAŽIJEME</div><h2>Tohle nebude obyčejná dovolená</h2></div></div><div class="grid">
<article class="card"><h3>Velkoměsto</h3><p>Shibuya, digitální teamLab a Akihabara, která vypadá jako kulisa z budoucnosti.</p></article>
<article class="card"><h3>Tradiční Japonsko</h3><p>Čajový obřad, samurajský workshop, chrámy a tisíce torii.</p></article>
<article class="card"><h3>Moře a ostrovy</h3><p>Mijadžima při západu slunce a dva pomalé dny na kolech a pláži Naošimy.</p></article>
</div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">KAPITOLY</div><h2>Sedm různých světů</h2></div></div><div class="grid">${data.cities.map(c=>chapterCard(c)).join('')}</div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">JAPONSKY BEZ ZMATKU</div><h2>Pár slov, která brzy uslyšíme</h2></div></div>${glossaryGrid(6)}<p><button class="btn outline" data-go="glossary">Otevřít celý slovníček</button></p></section>`;links()}
function glossaryGrid(limit){return `<div class="glossGrid">${data.glossary.slice(0,limit||data.glossary.length).map(g=>`<article class="glossCard"><div class="jp">${esc(g.jp)}</div><h3>${esc(g.term)}</h3><p>${esc(g.short)}</p><button data-term="${esc(g.term)}">Vysvětlit →</button></article>`).join('')}</div>`}
function chapters(){setActive('chapters');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">PŘÍBĚH CESTY</div><h2>Kapitoly</h2><div class="sub">Každá karta je klikací; informační štítky mají hranatější tvar a nejsou tlačítka.</div></div></div><div class="grid">${data.cities.map(c=>chapterCard(c)).join('')}</div></section>`;links()}
function chapter(id){
setActive('chapters');const c=data.cities.find(x=>x.id===id);const ds=data.days.filter(d=>d.chapter===id);
app.innerHTML=`<section class="chapterHero"><img src="./assets/chapter-${c.id}.svg"><div><div class="kicker">${esc(c.jp)}</div><h1>${esc(c.name)}</h1><p>${glossaryReplace(c.intro)}</p></div></section>
<section class="section"><div class="grid"><article class="card wide"><h2>Co nás čeká</h2>${chips(c.highlights)}<p style="margin-top:18px">${glossaryReplace(c.kids)}</p></article><article class="card"><h3>Ochutnáme</h3>${chips(c.food)}</article></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">DNY V TÉTO KAPITOLE</div><h2>Konkrétní plán</h2></div></div><article class="card full">${ds.map(d=>`<div class="dayCard"><div class="date">${d.date}</div><div><b>${esc(d.title)}</b><p>${glossaryReplace(d.story)}</p><button class="btn outline" data-go="day-${data.days.indexOf(d)}">Detail dne →</button></div></div>`).join('')}</article></section>`;links()}
function days(){setActive('days');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">DEN PO DNI</div><h2>Praktický itinerář</h2><div class="sub">Každý den má vlastní offline mapku a vysvětlení zastávek.</div></div></div><article class="card full">${data.days.map((d,i)=>`<div class="dayCard"><div class="date">${d.date}</div><div><b>${esc(d.title)}</b><p>${esc(d.city)} · ${glossaryReplace(d.story)}</p><button class="btn outline" data-go="day-${i}">Otevřít den →</button></div></div>`).join('')}</article></section>`;links()}
function day(i){
setActive('days');const d=data.days[i];app.innerHTML=`<section class="chapterHero" style="height:430px"><img src="./assets/chapter-${d.chapter}.svg"><div><div class="kicker">${d.date} · ${esc(d.city)}</div><h1 style="font-size:clamp(42px,7vw,72px)">${esc(d.title)}</h1><p>${glossaryReplace(d.story)}</p></div></section>
<section class="section"><div class="grid"><article class="card wide"><div class="timeline">${d.schedule.map(x=>`<div class="event"><div class="time">${esc(x[0])}</div><b>${esc(x[1])}</b><span>${glossaryReplace(x[2])}</span></div>`).join('')}</div></article><article class="card"><h3>Mise dne</h3>${d.missions.map(x=>`<p>${glossaryReplace(x)}</p>`).join('')}<h3>Ochutnat</h3>${chips(d.food)}</article></div></section>
<section class="section"><div class="inline-map"><img src="./assets/map-day-${i}.svg" alt="Schematická offline mapa dne"><div class="map-caption">Schematická mapa je součást aplikace a funguje offline. Nezobrazuje přesné měřítko, ale pořadí a hlavní body dne.</div></div></section>
<section class="section"><div class="grid"><article class="card"><h3>Stav dne</h3><label class="check"><input type="checkbox" data-check="d${i}a"> Připraveno</label><label class="check"><input type="checkbox" data-check="d${i}b"> Splněno</label><label class="check"><input type="checkbox" data-check="d${i}c"> Máme fotku dne</label></article><article class="card wide"><h3>Naše poznámka</h3><textarea data-note="d${i}" placeholder="Nejlepší moment, překvapení, změna plánu…"></textarea></article></div></section>`;restore();links()}
function food(){
setActive('food');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">JÍDLO V POŘADÍ CESTY</div><h2>Od prvního konbini po poslední sushi</h2><div class="sub">Řazeno chronologicky, s obrázkem, důvodem zastávky a místem na trase.</div></div></div><div class="foodTimeline">${data.restaurants.map(r=>`<article class="foodItem"><div class="foodDate">${esc(r.date)}</div><div class="foodVisual"><img src="./assets/food-${r.art}.svg" alt="${esc(r.type)}"></div><div class="foodBody"><div class="city">${esc(r.city)}</div><h3>${esc(r.name)}</h3><p>${glossaryReplace(r.why)}</p>${chips([r.type,r.order])}<div class="when">${esc(r.when)}</div><div class="foodMiniMap">${esc(r.map)}</div></div></article>`).join('')}</div></section>`;links()}
function glossary(){setActive('practical');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">MALÝ SLOVNÍČEK</div><h2>Co znamenají japonské výrazy</h2><div class="sub">Krátce, prakticky a bez učebnice.</div></div></div>${glossaryGrid()}</section>`;links()}
function practical(){setActive('practical');app.innerHTML=`<section class="section"><div class="sectionHead"><div><div class="kicker">PRAKTICKY</div><h2>Rezervace a poslední kontrola</h2></div></div><div class="grid"><article class="card wide"><h3>Pevné časy</h3>${data.reservations.map(r=>`<div class="res"><b>${r[0]}</b><span>${r[1]}</span><span>${esc(r[2])}</span></div>`).join('')}</article><article class="card"><h3>Před odletem</h3>${["Pasy a pojištění","eSIM","Suica","Adaptéry","Powerbanky","Pláštěnky a malé deštníky","SPF 50 a kšiltovky","Rezervace uložené offline"].map((x,i)=>`<label class="check"><input type="checkbox" data-check="p${i}"> ${x}</label>`).join('')}</article><article class="card full callout"><h3>Pravidlo tří</h3><p>Při každém přesunu: <b>mobil · peněženka/pas · batoh</b>. Nic dalšího není důležitější.</p></article></div></section>
<section class="section"><div class="sectionHead"><div><div class="kicker">SLOVNÍČEK</div><h2>Japonské pojmy</h2></div></div>${glossaryGrid(6)}<p><button class="btn outline" data-go="glossary">Zobrazit všechny</button></p></section>`;restore();links()}
function showTerm(term){const g=data.glossary.find(x=>x.term===term);if(!g)return;let modal=document.querySelector('#termModal');if(!modal){modal=document.createElement('div');modal.id='termModal';modal.className='modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="modalCard"><button class="btn outline" id="modalClose">Zavřít</button><div class="jp">${esc(g.jp)}</div><h2>${esc(g.term)}</h2><p><b>${esc(g.short)}</b></p><p>${esc(g.long)}</p></div>`;modal.classList.add('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};modal.querySelector('#modalClose').onclick=()=>modal.classList.remove('open')}
function restore(){document.querySelectorAll('[data-check]').forEach(x=>{x.checked=localStorage.getItem('c'+x.dataset.check)==='1';x.onchange=()=>localStorage.setItem('c'+x.dataset.check,x.checked?'1':'0')});document.querySelectorAll('[data-note]').forEach(x=>{x.value=localStorage.getItem('n'+x.dataset.note)||'';x.oninput=()=>localStorage.setItem('n'+x.dataset.note,x.value)})}
function go(v){close();window.scrollTo(0,0);location.hash=v;if(v==='home')home();else if(v==='chapters')chapters();else if(v==='days')days();else if(v==='food')food();else if(v==='practical')practical();else if(v==='glossary')glossary();else if(v.startsWith('chapter-'))chapter(v.slice(8));else if(v.startsWith('day-'))day(Number(v.slice(4)));else home()}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector('#menu').onclick=()=>{drawer.classList.add('open');shade.classList.add('open')};document.querySelector('#close').onclick=close;shade.onclick=close;
document.querySelector('#drawerNav').innerHTML=[['home','Úvod'],['chapters','Kapitoly'],['days','Den po dni'],['food','Jídlo'],['glossary','Slovníček'],['practical','Prakticky'],...data.cities.map(c=>['chapter-'+c.id,c.name])].map(x=>`<button data-drawer="${x[0]}">${esc(x[1])}</button>`).join('');document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>go(b.dataset.drawer));
document.querySelector('#mode').onclick=()=>{const d=document.documentElement.dataset.dark==='1'?'0':'1';document.documentElement.dataset.dark=d;localStorage.setItem('dark',d)};document.documentElement.dataset.dark=localStorage.getItem('dark')||'0';
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');go(location.hash.slice(1)||'home');
